lrpc:
  protocol:
    serializer: JSON
  client:
    address-max-connection: 1001
    load-balance: ROUND_ROBIN
  server:
    port: 23923
    worker-max: 1001

spring:
  application:
    name: lrpc-example